# Generated by Django 4.2.7 on 2024-01-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_unit_parent_alter_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='slug',
            field=models.SlugField(default='None'),
        ),
    ]
