# Generated by Django 4.2.7 on 2024-01-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_unit_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='None'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='None'),
        ),
    ]
