# Generated by Django 4.2.7 on 2024-01-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_brand_slug_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='slug',
            field=models.SlugField(default='None', max_length=128, verbose_name='url-адрес'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='None', max_length=128, verbose_name='url-адрес'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='None', max_length=128, verbose_name='url-адрес'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='slug',
            field=models.SlugField(default='None', max_length=128, verbose_name='url-адрес'),
        ),
    ]
